services:
  app:
    build:
      context: ../  # raiz do projeto: inclui app/ e docker/
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../app:/var/www
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ../app:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - laravel-network

volumes:
  mysql-data:
    driver: local

networks:
  laravel-network:
    driver: bridge
